version: '2.5'

services:
  couchserver:
    image: couchdb:2.3
    volumes:
      - ./dbdata:/opt/couchdb/data
    network_mode: 'host'
    environment:
      COUCHDB_USER: software-libre
      COUCHDB_PASSWORD: software-libre
    #ports:
    #  - "5984:5984"
    restart: always
    
  cliente-web:
    image: img-cliente-web
    container_name: container-cliente-web
    network_mode: 'host'
    depends_on:
      - couchserver
    #ports:
    #  - "3000:3000"
    links:
      - couchserver
  
  cliente-1:
    image: img-cliente-consola
    container_name: container-cliente-consola-1
    entrypoint: /bin/sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      DB_HOST: 127.0.0.1:5984
      DB_NAME: software-libre-database
      MODE: manual
      DB_USER: ''
      DB_PASS: ''
    network_mode: 'host'
    depends_on:
      - couchserver
    links:
      - couchserver
      
  cliente-2:
    image: img-cliente-consola
    container_name: container-cliente-consola-2
    environment:
      DB_HOST: 127.0.0.1:5984
      DB_NAME: software-libre-database
      MODE: auto
      DB_USER: ''
      DB_PASS: ''
    network_mode: 'host'
    depends_on:
      - couchserver
    links:
      - couchserver

